platform :ios, '8.0'
use_frameworks!

target ‘HATHandyKitFramework’ do
project 'HATHandyKitFramework/HATHandyKitFramework.xcodeproj'
pod 'Masonry', '1.0.2'
pod 'MJRefresh', '3.1.12'
pod 'MBProgressHUD', '1.0.0'
pod 'SDWebImage', '4.0.0'
pod 'YTKNetwork', '2.0.3'

#支持控制台显示中文
#pod 'HYBUnicodeReadable', '~> 1.1'
#pod 'JSONModel'
#pod 'TBActionSheet'
#pod 'CocoaLumberjack'

end
